### ISSUE TITLE
{ "name": "绿裙大学", "institute": "GitHub学院", "description": "", "deadline": "2024-06-26T00:00:00+08:00", "website": "http://github.com/", "tags": [], "target": "camp2024" }

### ISSUE THREAD

**Issue by fanshuifanshui** [CS-BAOYAN/BoardCaster#52]
> 错误投稿格式
{
"name": "绿裙大学",
"institute": "GitHub学院",
"description": "",
"deadline": "2024-06-26T00:00:00+08:00",
"website": "http://github.com/",
"tags": [],
"target": "camp2024"
}

**Comment by Axi404** [comment]
这并非正确的投稿格式，我将删除内容并 close issue
